"""empty message

Revision ID: 1e1c05d03ff9
Revises: 
Create Date: 2022-06-24 11:30:04.236060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1c05d03ff9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('emai', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('date_joined', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('doc', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('time', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('remarks', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'remarks')
    op.drop_column('user', 'time')
    op.drop_column('user', 'doc')
    op.drop_column('user', 'date_joined')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'emai')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
