"""empty message

Revision ID: 31836f41de23
Revises: 
Create Date: 2022-07-20 20:09:43.281039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31836f41de23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('two_factor_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'two_factor_enabled')
    # ### end Alembic commands ###
