"""empty message

Revision ID: 5137f9547465
Revises: 
Create Date: 2022-07-11 20:19:35.714528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5137f9547465'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userappointment')
    op.add_column('user', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('date_joined', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('doc', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('time', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('remarks', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'remarks')
    op.drop_column('user', 'time')
    op.drop_column('user', 'doc')
    op.drop_column('user', 'date_joined')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.create_table('userappointment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('date_joined', sa.VARCHAR(length=50), nullable=True),
    sa.Column('doc', sa.VARCHAR(length=60), nullable=True),
    sa.Column('time', sa.VARCHAR(length=30), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=30), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
