"""empty message

Revision ID: 8645817ace08
Revises: 
Create Date: 2022-07-07 09:07:04.688938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8645817ace08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userappointment', sa.Column('email', sa.String(length=120), nullable=True))
    op.drop_column('userappointment', 'emai')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userappointment', sa.Column('emai', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('userappointment', 'email')
    # ### end Alembic commands ###
