"""empty message

Revision ID: 8b367084d060
Revises: 
Create Date: 2022-07-18 22:49:51.056390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b367084d060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('card_name', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('card_no', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('card_exp_month', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('card_exp_year', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('card_CVV', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'card_CVV')
    op.drop_column('user', 'card_exp_year')
    op.drop_column('user', 'card_exp_month')
    op.drop_column('user', 'card_no')
    op.drop_column('user', 'card_name')
    # ### end Alembic commands ###
