"""empty message

Revision ID: be05528221d2
Revises: 
Create Date: 2022-08-01 13:15:10.691172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be05528221d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'card_CVV')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('card_CVV', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
