"""empty message

Revision ID: c0ad10875c95
Revises: 
Create Date: 2022-07-22 16:33:07.318962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ad10875c95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('banned', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('verified', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified')
    op.drop_column('user', 'banned')
    # ### end Alembic commands ###
