"""empty message

Revision ID: fea7c4af5fa9
Revises: 
Create Date: 2022-08-11 15:40:01.832425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea7c4af5fa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('shipping_address', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('unit_no', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('phone_no', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_no')
    op.drop_column('user', 'unit_no')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'shipping_address')
    # ### end Alembic commands ###
